# Generated by Django 5.1.1 on 2024-11-06 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="group",
        ),
        migrations.RemoveField(
            model_name="post",
            name="vision_board",
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="visionboard",
            name="group",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vision_board",
                to="projecta10.group",
            ),
        ),
    ]
