# Generated by Django 5.1.1 on 2024-11-06 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0003_alter_post_user_alter_visionboard_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visionboard",
            name="group",
        ),
        migrations.RemoveField(
            model_name="message",
            name="group",
        ),
        migrations.AddField(
            model_name="visionboard",
            name="members",
            field=models.ManyToManyField(
                related_name="vision_boards", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
