# Generated by Django 5.1.1 on 2024-11-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0004_remove_visionboard_group_remove_message_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
