# Generated by Django 5.1.1 on 2024-11-06 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0006_post_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
