# Generated by Django 5.1.1 on 2024-11-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0007_delete_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light Mode"), ("dark", "Dark Mode")],
                default="light",
                help_text="Select your preferred theme.",
                max_length=10,
            ),
        ),
    ]
