# Generated by Django 5.1.1 on 2024-11-14 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0008_customuser_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="vision_board",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="projecta10.visionboard",
            ),
        ),
    ]
