# Generated by Django 5.1.1 on 2024-11-17 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0009_message_vision_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="vision_board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vision_board",
                to="projecta10.visionboard",
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "Image"),
                    ("text", "Text"),
                    ("pdf", "PDF"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="projecta10.uploadedfile",
            ),
        ),
    ]
