# Generated by Django 5.1.1 on 2024-11-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0010_post_vision_board_uploadedfile_file_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="vision_board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="projecta10.visionboard",
            ),
        ),
    ]
