# Generated by Django 5.1.1 on 2024-12-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0011_uploadedfile_vision_board"),
        ("projecta10", "0013_alter_inbox_user"),
    ]

    operations = []
