# Generated by Django 5.1.1 on 2024-12-01 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0014_merge_20241201_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="vision_board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="projecta10.visionboard",
            ),
        ),
    ]
