# Generated by Django 5.1.1 on 2024-12-01 23:36

from django.db import migrations

from projecta10.models.base import CustomUser, Inbox


def create_inboxes(apps, schema_editor):
    for user in CustomUser.objects.all():
        if not Inbox.objects.filter(user=user).exists():
            Inbox.objects.create(user=user)
            print(f"Inbox created for: {user.username}")
        else:
            print(f"Inbox already exists for: {user.username}")


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0015_joinrequest_vision_board"),
    ]

    operations = [
        migrations.RunPython(create_inboxes),
    ]
