# Generated by Django 5.1.1 on 2024-12-02 02:58

from datetime import timezone

from django.db import migrations

from projecta10.models.base import CustomUser


def add_join_date(apps, schema_editor):
    for user in CustomUser.objects.all():
        if user.date_joined is None:
            user.date_joined = timezone.now()
            user.save()
            print(f"Join date backfilled for: {user.username}")
        else:
            print(f"Join date already exists for: {user.username}")


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0017_alter_customuser_date_joined"),
    ]

    operations = [
        migrations.RunPython(add_join_date),
    ]
