# Generated by Django 5.1.1 on 2024-12-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0018_add_join_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="visionboard",
            name="websocket_name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
