# Generated by Django 5.1.1 on 2024-12-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta10', '0019_visionboard_websocket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionboard',
            name='description',
            field=models.TextField(default='This Vision Board was created by <django.db.models.fields.related.ForeignKey>.'),
        ),
        migrations.AlterField(
            model_name='visionboard',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
