# Generated by Django 5.1.1 on 2024-12-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta10', '0020_visionboard_description_alter_visionboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionboard',
            name='description',
            field=models.TextField(),
        ),
    ]
