# Generated by Django 5.1.1 on 2024-12-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projecta10", "0020_alter_post_caption"),
        ("projecta10", "0021_alter_visionboard_description"),
    ]

    operations = []
